[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = [
  'cd backend && bundle install',
  'cd frontend && npm install --production=false'
]

[phases.build]
cmds = [
  'cd frontend && npm run build && cd ..',
  'rm -rf backend/public/*',
  'cp -r frontend/dist/* backend/public/'
]

[start]
cmd = 'cd backend && bundle exec rails db:migrate && bundle exec rails server -p ${PORT:-3000} -e production'
